Update gitlab-ci.yml

diff --git a/.github/workflows/gitlab-ci.yml b/.github/workflows/gitlab-ci.yml
--- a/.github/workflows/gitlab-ci.yml
+++ b/.github/workflows/gitlab-ci.yml
@@ -13,6 +13,13 @@ jobs:
       - name: Checkout repo
         uses: actions/checkout@v3
 
+      - name: Check if Dockerfile exists
+        run: |
+          if [ ! -f Dockerfile ]; then
+            echo "Dockerfile not found!"
+            exit 1
+          fi
+
       - name: Setup QEMU
         uses: docker/setup-qemu-action@v2
 
@@ -89,12 +96,16 @@ jobs:
       - name: Transfer and run deploy script
         uses: appleboy/ssh-action@v0.1.4
         with:
-          host: 167.86.88.17 # IP dur
+          host: 167.86.88.17 # Remplacez par l'IP de votre VPS
           username: ${{ secrets.VPS_ADMIN_USER }}
           password: ${{ secrets.VPS_SSH_PASSWORD }}
           port: 22
           script: |
             set -e
-            scp -o StrictHostKeyChecking=no deploy_n8n.sh ${DEPLOY_USER}@167.86.88.17:/home/${DEPLOY_USER}/deploy_n8n.sh
+            # Copier le script deploy_n8n.sh depuis GitHub vers le VPS
+            scp -o StrictHostKeyChecking=no ./scripts/deploy_n8n.sh ${DEPLOY_USER}@167.86.88.17:/home/${DEPLOY_USER}/deploy_n8n.sh
+            # Rendre le script exécutable
             ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@167.86.88.17 "chmod +x /home/${DEPLOY_USER}/deploy_n8n.sh"
+            # Exécuter le script de déploiement
             ssh -o StrictHostKeyChecking=no ${DEPLOY_USER}@167.86.88.17 "/home/${DEPLOY_USER}/deploy_n8n.sh wezoun/n8n:latest"
+
